//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSLab.User
{
    using System;
    using TSLab.Script;
    
    
    public sealed class Script
    {
        
        private TSLab.Script.Handlers.Compress Сжать1_h = new TSLab.Script.Handlers.Compress();
        
        public TSLab.Script.Optimization.OptimProperty Сжать1_Shift = new TSLab.Script.Optimization.OptimProperty(0, 0, 60, 5);
        
        public void Execute(TSLab.Script.Handlers.IContext context, TSLab.Script.ISecurity Источник1)
        {
            // Initialize 'Сжать1' item
            this.Сжать1_h.Interval = 300;
            this.Сжать1_h.Shift = this.Сжать1_Shift;
            // Make 'Сжать1' item data
            TSLab.Script.ISecurity Сжать1;
            try
            {
                Сжать1 = this.Сжать1_h.Execute(Источник1);
            }
            catch (System.ArgumentOutOfRangeException )
            {
                throw new TSLab.Script.ScriptException("Ошибка при вычислении блока \'Сжать1\'. Индекс за пределам диапазона.");
            }
            // =================================================
            // Panels
            // =================================================
            // Make 'Главная' pane
            TSLab.Script.IPane Главная_pane = context.CreatePane("Главная", 70D, false);
            Главная_pane.Visible = true;
            // =================================================
            // Handlers
            // =================================================
            // =================================================
            // Trading
            // =================================================
            int barsCount = Источник1.Bars.Count;
            if ((context.IsLastBarUsed == false))
            {
                barsCount--;
            }
            for (int i = 0; (i < barsCount); i++)
            {
            }
            // =================================================
            // Charts
            // =================================================
            // Make 'Источник1' chart
            TSLab.Script.IGraphList Главная_pane_Источник1_chart = Главная_pane.AddList(("Источник1" 
                            + (" [" 
                            + (Источник1.Symbol + "]"))), Источник1, TSLab.Script.CandleStyles.BAR_CANDLE, true, true, true, true, 255, TSLab.Script.PaneSides.RIGHT);
            Источник1.ConnectSecurityList(Главная_pane_Источник1_chart);
            Главная_pane_Источник1_chart.AlternativeColor = 255;
            Главная_pane.UpdatePrecision(TSLab.Script.PaneSides.RIGHT, Источник1.Decimals);
            // Make 'Сжать1' chart
            TSLab.Script.IGraphList Главная_pane_Сжать1_chart = Главная_pane.AddList((((("Сжать1" 
                            + (" (" + this.Сжать1_h.Interval)) 
                            + (", " + this.Сжать1_h.Shift)) 
                            + ")") 
                            + (" [" 
                            + (Сжать1.Symbol + "]"))), Сжать1, TSLab.Script.CandleStyles.BAR_CANDLE, true, true, true, true, 41472, TSLab.Script.PaneSides.LEFT);
            Сжать1.ConnectSecurityList(Главная_pane_Сжать1_chart);
            Главная_pane.UpdatePrecision(TSLab.Script.PaneSides.LEFT, Сжать1.Decimals);
        }
    }
}
